-- Insert 5 test users into auth.users
INSERT INTO
  "auth"."users" (
    "id",
    "instance_id",
    "aud",
    "role",
    "email",
    "encrypted_password",
    "email_confirmed_at",
    "invited_at",
    "confirmation_token",
    "confirmation_sent_at",
    "recovery_token",
    "recovery_sent_at",
    "email_change_token_new",
    "email_change",
    "email_change_sent_at",
    "last_sign_in_at",
    "raw_app_meta_data",
    "raw_user_meta_data",
    "is_super_admin",
    "created_at",
    "updated_at",
    "phone",
    "phone_confirmed_at",
    "phone_change",
    "phone_change_token",
    "phone_change_sent_at",
    "email_change_token_current",
    "email_change_confirm_status",
    "banned_until",
    "reauthentication_token",
    "reauthentication_sent_at",
    "is_sso_user",
    "deleted_at",
    "is_anonymous"
  ) VALUES
  (
    '00000000-0000-0000-0000-000000000001',
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'user1@gmail.com',
    crypt('password123', gen_salt('bf')),
    now(),
    NULL,
    '',
    now(),
    '',
    NULL,
    '',
    '',
    NULL,
    now(),
    '{"provider":"email","providers":["email"]}',
    '{}',
    false,
    now(),
    now(),
    NULL,
    NULL,
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL,
    false,
    NULL,
    false
  ),
  (
    '00000000-0000-0000-0000-000000000002',
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'user2@gmail.com',
    crypt('password123', gen_salt('bf')),
    now(),
    NULL,
    '',
    now(),
    '',
    NULL,
    '',
    '',
    NULL,
    now(),
    '{"provider":"email","providers":["email"]}',
    '{}',
    false,
    now(),
    now(),
    NULL,
    NULL,
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL,
    false,
    NULL,
    false
  ),
  (
    '00000000-0000-0000-0000-000000000003',
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'user3@gmail.com',
    crypt('password123', gen_salt('bf')),
    now(),
    NULL,
    '',
    now(),
    '',
    NULL,
    '',
    '',
    NULL,
    now(),
    '{"provider":"email","providers":["email"]}',
    '{}',
    false,
    now(),
    now(),
    NULL,
    NULL,
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL,
    false,
    NULL,
    false
  ),
  (
    '00000000-0000-0000-0000-000000000004',
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'user4@gmail.com',
    crypt('password123', gen_salt('bf')),
    now(),
    NULL,
    '',
    now(),
    '',
    NULL,
    '',
    '',
    NULL,
    now(),
    '{"provider":"email","providers":["email"]}',
    '{}',
    false,
    now(),
    now(),
    NULL,
    NULL,
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL,
    false,
    NULL,
    false
  ),
  (
    '00000000-0000-0000-0000-000000000005',
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'user5@gmail.com',
    crypt('password123', gen_salt('bf')),
    now(),
    NULL,
    '',
    now(),
    '',
    NULL,
    '',
    '',
    NULL,
    now(),
    '{"provider":"email","providers":["email"]}',
    '{}',
    false,
    now(),
    now(),
    NULL,
    NULL,
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL,
    false,
    NULL,
    false
  );

-- Insert realistic sensor data for the last 24 hours
-- Create readings spread over time with realistic variations

-- Helper: Generate timestamps for the last 24 hours (48 readings per sensor, one every 30 minutes)
-- pH sensor data (Range: 6.8-7.5, Threshold: 5.5-8.5, Status: mostly compliant)
INSERT INTO "public"."sensor_data" ("type", "unit", "value", "recorded_at") VALUES
  -- 24 hours ago to 12 hours ago
  ('ph', 'pH', 7.15, now() - interval '24 hours'),
  ('ph', 'pH', 7.22, now() - interval '23.5 hours'),
  ('ph', 'pH', 7.18, now() - interval '23 hours'),
  ('ph', 'pH', 7.25, now() - interval '22.5 hours'),
  ('ph', 'pH', 7.12, now() - interval '22 hours'),
  ('ph', 'pH', 7.08, now() - interval '21.5 hours'),
  ('ph', 'pH', 7.19, now() - interval '21 hours'),
  ('ph', 'pH', 7.23, now() - interval '20.5 hours'),
  ('ph', 'pH', 7.16, now() - interval '20 hours'),
  ('ph', 'pH', 7.28, now() - interval '19.5 hours'),
  ('ph', 'pH', 7.21, now() - interval '19 hours'),
  ('ph', 'pH', 7.14, now() - interval '18.5 hours'),
  ('ph', 'pH', 7.17, now() - interval '18 hours'),
  ('ph', 'pH', 7.11, now() - interval '17.5 hours'),
  ('ph', 'pH', 7.24, now() - interval '17 hours'),
  ('ph', 'pH', 7.19, now() - interval '16.5 hours'),
  ('ph', 'pH', 7.26, now() - interval '16 hours'),
  ('ph', 'pH', 7.13, now() - interval '15.5 hours'),
  ('ph', 'pH', 7.20, now() - interval '15 hours'),
  ('ph', 'pH', 7.18, now() - interval '14.5 hours'),
  ('ph', 'pH', 7.22, now() - interval '14 hours'),
  ('ph', 'pH', 7.15, now() - interval '13.5 hours'),
  ('ph', 'pH', 7.27, now() - interval '13 hours'),
  ('ph', 'pH', 7.16, now() - interval '12.5 hours'),
  -- 12 hours ago to now (more recent data)
  ('ph', 'pH', 7.21, now() - interval '12 hours'),
  ('ph', 'pH', 7.14, now() - interval '11.5 hours'),
  ('ph', 'pH', 7.19, now() - interval '11 hours'),
  ('ph', 'pH', 7.23, now() - interval '10.5 hours'),
  ('ph', 'pH', 7.17, now() - interval '10 hours'),
  ('ph', 'pH', 7.25, now() - interval '9.5 hours'),
  ('ph', 'pH', 7.12, now() - interval '9 hours'),
  ('ph', 'pH', 7.20, now() - interval '8.5 hours'),
  ('ph', 'pH', 7.18, now() - interval '8 hours'),
  ('ph', 'pH', 7.22, now() - interval '7.5 hours'),
  ('ph', 'pH', 7.16, now() - interval '7 hours'),
  ('ph', 'pH', 7.24, now() - interval '6.5 hours'),
  ('ph', 'pH', 7.13, now() - interval '6 hours'),
  ('ph', 'pH', 7.19, now() - interval '5.5 hours'),
  ('ph', 'pH', 7.21, now() - interval '5 hours'),
  ('ph', 'pH', 7.15, now() - interval '4.5 hours'),
  ('ph', 'pH', 7.26, now() - interval '4 hours'),
  ('ph', 'pH', 7.18, now() - interval '3.5 hours'),
  ('ph', 'pH', 7.23, now() - interval '3 hours'),
  ('ph', 'pH', 7.17, now() - interval '2.5 hours'),
  ('ph', 'pH', 7.14, now() - interval '2 hours'),
  ('ph', 'pH', 7.22, now() - interval '1.5 hours'),
  ('ph', 'pH', 7.19, now() - interval '1 hour'),
  ('ph', 'pH', 7.16, now() - interval '30 minutes'),
  ('ph', 'pH', 7.20, now() - interval '5 minutes');

-- Dissolved Oxygen sensor data (Range: 5.5-7.2 mg/L, Threshold: >= 5 mg/L, Status: compliant)
INSERT INTO "public"."sensor_data" ("type", "unit", "value", "recorded_at") VALUES
  ('dissolved_oxygen', 'mg/L', 6.45, now() - interval '24 hours'),
  ('dissolved_oxygen', 'mg/L', 6.52, now() - interval '23.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.38, now() - interval '23 hours'),
  ('dissolved_oxygen', 'mg/L', 6.61, now() - interval '22.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.48, now() - interval '22 hours'),
  ('dissolved_oxygen', 'mg/L', 6.55, now() - interval '21.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.42, now() - interval '21 hours'),
  ('dissolved_oxygen', 'mg/L', 6.68, now() - interval '20.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.51, now() - interval '20 hours'),
  ('dissolved_oxygen', 'mg/L', 6.73, now() - interval '19.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.46, now() - interval '19 hours'),
  ('dissolved_oxygen', 'mg/L', 6.59, now() - interval '18.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.44, now() - interval '18 hours'),
  ('dissolved_oxygen', 'mg/L', 6.67, now() - interval '17.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.53, now() - interval '17 hours'),
  ('dissolved_oxygen', 'mg/L', 6.71, now() - interval '16.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.49, now() - interval '16 hours'),
  ('dissolved_oxygen', 'mg/L', 6.56, now() - interval '15.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.62, now() - interval '15 hours'),
  ('dissolved_oxygen', 'mg/L', 6.47, now() - interval '14.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.54, now() - interval '14 hours'),
  ('dissolved_oxygen', 'mg/L', 6.65, now() - interval '13.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.58, now() - interval '13 hours'),
  ('dissolved_oxygen', 'mg/L', 6.43, now() - interval '12.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.69, now() - interval '12 hours'),
  ('dissolved_oxygen', 'mg/L', 6.52, now() - interval '11.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.60, now() - interval '11 hours'),
  ('dissolved_oxygen', 'mg/L', 6.48, now() - interval '10.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.64, now() - interval '10 hours'),
  ('dissolved_oxygen', 'mg/L', 6.51, now() - interval '9.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.72, now() - interval '9 hours'),
  ('dissolved_oxygen', 'mg/L', 6.45, now() - interval '8.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.57, now() - interval '8 hours'),
  ('dissolved_oxygen', 'mg/L', 6.63, now() - interval '7.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.49, now() - interval '7 hours'),
  ('dissolved_oxygen', 'mg/L', 6.66, now() - interval '6.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.53, now() - interval '6 hours'),
  ('dissolved_oxygen', 'mg/L', 6.70, now() - interval '5.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.46, now() - interval '5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.61, now() - interval '4.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.55, now() - interval '4 hours'),
  ('dissolved_oxygen', 'mg/L', 6.68, now() - interval '3.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.47, now() - interval '3 hours'),
  ('dissolved_oxygen', 'mg/L', 6.59, now() - interval '2.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.52, now() - interval '2 hours'),
  ('dissolved_oxygen', 'mg/L', 6.64, now() - interval '1.5 hours'),
  ('dissolved_oxygen', 'mg/L', 6.48, now() - interval '1 hour'),
  ('dissolved_oxygen', 'mg/L', 6.56, now() - interval '30 minutes'),
  ('dissolved_oxygen', 'mg/L', 6.50, now() - interval '5 minutes');

-- Turbidity sensor data (Range: 35-65 NTU, Threshold: <= 50 NTU, Status: some violations)
INSERT INTO "public"."sensor_data" ("type", "unit", "value", "recorded_at") VALUES
  ('turbidity', 'NTU', 42.5, now() - interval '24 hours'),
  ('turbidity', 'NTU', 45.2, now() - interval '23.5 hours'),
  ('turbidity', 'NTU', 48.8, now() - interval '23 hours'),
  ('turbidity', 'NTU', 51.3, now() - interval '22.5 hours'),
  ('turbidity', 'NTU', 53.7, now() - interval '22 hours'),
  ('turbidity', 'NTU', 49.6, now() - interval '21.5 hours'),
  ('turbidity', 'NTU', 46.4, now() - interval '21 hours'),
  ('turbidity', 'NTU', 43.9, now() - interval '20.5 hours'),
  ('turbidity', 'NTU', 47.2, now() - interval '20 hours'),
  ('turbidity', 'NTU', 52.1, now() - interval '19.5 hours'),
  ('turbidity', 'NTU', 54.8, now() - interval '19 hours'),
  ('turbidity', 'NTU', 50.9, now() - interval '18.5 hours'),
  ('turbidity', 'NTU', 48.3, now() - interval '18 hours'),
  ('turbidity', 'NTU', 44.7, now() - interval '17.5 hours'),
  ('turbidity', 'NTU', 41.5, now() - interval '17 hours'),
  ('turbidity', 'NTU', 39.2, now() - interval '16.5 hours'),
  ('turbidity', 'NTU', 37.8, now() - interval '16 hours'),
  ('turbidity', 'NTU', 40.6, now() - interval '15.5 hours'),
  ('turbidity', 'NTU', 43.4, now() - interval '15 hours'),
  ('turbidity', 'NTU', 46.8, now() - interval '14.5 hours'),
  ('turbidity', 'NTU', 49.2, now() - interval '14 hours'),
  ('turbidity', 'NTU', 52.5, now() - interval '13.5 hours'),
  ('turbidity', 'NTU', 55.3, now() - interval '13 hours'),
  ('turbidity', 'NTU', 57.9, now() - interval '12.5 hours'),
  ('turbidity', 'NTU', 59.6, now() - interval '12 hours'),
  ('turbidity', 'NTU', 61.2, now() - interval '11.5 hours'),
  ('turbidity', 'NTU', 58.4, now() - interval '11 hours'),
  ('turbidity', 'NTU', 55.7, now() - interval '10.5 hours'),
  ('turbidity', 'NTU', 53.1, now() - interval '10 hours'),
  ('turbidity', 'NTU', 50.8, now() - interval '9.5 hours'),
  ('turbidity', 'NTU', 48.5, now() - interval '9 hours'),
  ('turbidity', 'NTU', 46.3, now() - interval '8.5 hours'),
  ('turbidity', 'NTU', 44.1, now() - interval '8 hours'),
  ('turbidity', 'NTU', 47.6, now() - interval '7.5 hours'),
  ('turbidity', 'NTU', 50.2, now() - interval '7 hours'),
  ('turbidity', 'NTU', 52.9, now() - interval '6.5 hours'),
  ('turbidity', 'NTU', 54.5, now() - interval '6 hours'),
  ('turbidity', 'NTU', 56.8, now() - interval '5.5 hours'),
  ('turbidity', 'NTU', 58.2, now() - interval '5 hours'),
  ('turbidity', 'NTU', 59.7, now() - interval '4.5 hours'),
  ('turbidity', 'NTU', 57.3, now() - interval '4 hours'),
  ('turbidity', 'NTU', 55.6, now() - interval '3.5 hours'),
  ('turbidity', 'NTU', 53.4, now() - interval '3 hours'),
  ('turbidity', 'NTU', 51.8, now() - interval '2.5 hours'),
  ('turbidity', 'NTU', 54.2, now() - interval '2 hours'),
  ('turbidity', 'NTU', 56.5, now() - interval '1.5 hours'),
  ('turbidity', 'NTU', 57.9, now() - interval '1 hour'),
  ('turbidity', 'NTU', 58.6, now() - interval '30 minutes'),
  ('turbidity', 'NTU', 58.0, now() - interval '5 minutes');

-- Conductivity sensor data (Range: 1800-2500 µS/cm, Threshold: <= 3000 µS/cm, Status: compliant)
INSERT INTO "public"."sensor_data" ("type", "unit", "value", "recorded_at") VALUES
  ('conductivity', 'µS/cm', 2050, now() - interval '24 hours'),
  ('conductivity', 'µS/cm', 2120, now() - interval '23.5 hours'),
  ('conductivity', 'µS/cm', 2085, now() - interval '23 hours'),
  ('conductivity', 'µS/cm', 2165, now() - interval '22.5 hours'),
  ('conductivity', 'µS/cm', 2140, now() - interval '22 hours'),
  ('conductivity', 'µS/cm', 2095, now() - interval '21.5 hours'),
  ('conductivity', 'µS/cm', 2180, now() - interval '21 hours'),
  ('conductivity', 'µS/cm', 2210, now() - interval '20.5 hours'),
  ('conductivity', 'µS/cm', 2175, now() - interval '20 hours'),
  ('conductivity', 'µS/cm', 2240, now() - interval '19.5 hours'),
  ('conductivity', 'µS/cm', 2195, now() - interval '19 hours'),
  ('conductivity', 'µS/cm', 2155, now() - interval '18.5 hours'),
  ('conductivity', 'µS/cm', 2125, now() - interval '18 hours'),
  ('conductivity', 'µS/cm', 2090, now() - interval '17.5 hours'),
  ('conductivity', 'µS/cm', 2060, now() - interval '17 hours'),
  ('conductivity', 'µS/cm', 2035, now() - interval '16.5 hours'),
  ('conductivity', 'µS/cm', 2070, now() - interval '16 hours'),
  ('conductivity', 'µS/cm', 2105, now() - interval '15.5 hours'),
  ('conductivity', 'µS/cm', 2140, now() - interval '15 hours'),
  ('conductivity', 'µS/cm', 2170, now() - interval '14.5 hours'),
  ('conductivity', 'µS/cm', 2205, now() - interval '14 hours'),
  ('conductivity', 'µS/cm', 2235, now() - interval '13.5 hours'),
  ('conductivity', 'µS/cm', 2260, now() - interval '13 hours'),
  ('conductivity', 'µS/cm', 2285, now() - interval '12.5 hours'),
  ('conductivity', 'µS/cm', 2310, now() - interval '12 hours'),
  ('conductivity', 'µS/cm', 2280, now() - interval '11.5 hours'),
  ('conductivity', 'µS/cm', 2245, now() - interval '11 hours'),
  ('conductivity', 'µS/cm', 2220, now() - interval '10.5 hours'),
  ('conductivity', 'µS/cm', 2185, now() - interval '10 hours'),
  ('conductivity', 'µS/cm', 2160, now() - interval '9.5 hours'),
  ('conductivity', 'µS/cm', 2130, now() - interval '9 hours'),
  ('conductivity', 'µS/cm', 2095, now() - interval '8.5 hours'),
  ('conductivity', 'µS/cm', 2075, now() - interval '8 hours'),
  ('conductivity', 'µS/cm', 2110, now() - interval '7.5 hours'),
  ('conductivity', 'µS/cm', 2145, now() - interval '7 hours'),
  ('conductivity', 'µS/cm', 2175, now() - interval '6.5 hours'),
  ('conductivity', 'µS/cm', 2200, now() - interval '6 hours'),
  ('conductivity', 'µS/cm', 2230, now() - interval '5.5 hours'),
  ('conductivity', 'µS/cm', 2255, now() - interval '5 hours'),
  ('conductivity', 'µS/cm', 2220, now() - interval '4.5 hours'),
  ('conductivity', 'µS/cm', 2190, now() - interval '4 hours'),
  ('conductivity', 'µS/cm', 2165, now() - interval '3.5 hours'),
  ('conductivity', 'µS/cm', 2135, now() - interval '3 hours'),
  ('conductivity', 'µS/cm', 2110, now() - interval '2.5 hours'),
  ('conductivity', 'µS/cm', 2085, now() - interval '2 hours'),
  ('conductivity', 'µS/cm', 2120, now() - interval '1.5 hours'),
  ('conductivity', 'µS/cm', 2095, now() - interval '1 hour'),
  ('conductivity', 'µS/cm', 2105, now() - interval '30 minutes'),
  ('conductivity', 'µS/cm', 2100, now() - interval '5 minutes');

-- Flow Rate sensor data (Range: 65-85 m³/h, Threshold: <= 100 m³/h, Status: compliant)
INSERT INTO "public"."sensor_data" ("type", "unit", "value", "recorded_at") VALUES
  ('flow_rate', 'm³/h', 72.5, now() - interval '24 hours'),
  ('flow_rate', 'm³/h', 74.8, now() - interval '23.5 hours'),
  ('flow_rate', 'm³/h', 73.2, now() - interval '23 hours'),
  ('flow_rate', 'm³/h', 76.5, now() - interval '22.5 hours'),
  ('flow_rate', 'm³/h', 78.3, now() - interval '22 hours'),
  ('flow_rate', 'm³/h', 75.9, now() - interval '21.5 hours'),
  ('flow_rate', 'm³/h', 73.6, now() - interval '21 hours'),
  ('flow_rate', 'm³/h', 71.4, now() - interval '20.5 hours'),
  ('flow_rate', 'm³/h', 69.8, now() - interval '20 hours'),
  ('flow_rate', 'm³/h', 68.2, now() - interval '19.5 hours'),
  ('flow_rate', 'm³/h', 70.5, now() - interval '19 hours'),
  ('flow_rate', 'm³/h', 72.9, now() - interval '18.5 hours'),
  ('flow_rate', 'm³/h', 74.6, now() - interval '18 hours'),
  ('flow_rate', 'm³/h', 76.8, now() - interval '17.5 hours'),
  ('flow_rate', 'm³/h', 78.4, now() - interval '17 hours'),
  ('flow_rate', 'm³/h', 80.2, now() - interval '16.5 hours'),
  ('flow_rate', 'm³/h', 81.7, now() - interval '16 hours'),
  ('flow_rate', 'm³/h', 83.5, now() - interval '15.5 hours'),
  ('flow_rate', 'm³/h', 84.9, now() - interval '15 hours'),
  ('flow_rate', 'm³/h', 82.3, now() - interval '14.5 hours'),
  ('flow_rate', 'm³/h', 79.6, now() - interval '14 hours'),
  ('flow_rate', 'm³/h', 77.2, now() - interval '13.5 hours'),
  ('flow_rate', 'm³/h', 75.8, now() - interval '13 hours'),
  ('flow_rate', 'm³/h', 73.4, now() - interval '12.5 hours'),
  ('flow_rate', 'm³/h', 71.9, now() - interval '12 hours'),
  ('flow_rate', 'm³/h', 70.3, now() - interval '11.5 hours'),
  ('flow_rate', 'm³/h', 72.1, now() - interval '11 hours'),
  ('flow_rate', 'm³/h', 74.5, now() - interval '10.5 hours'),
  ('flow_rate', 'm³/h', 76.2, now() - interval '10 hours'),
  ('flow_rate', 'm³/h', 78.6, now() - interval '9.5 hours'),
  ('flow_rate', 'm³/h', 80.8, now() - interval '9 hours'),
  ('flow_rate', 'm³/h', 82.4, now() - interval '8.5 hours'),
  ('flow_rate', 'm³/h', 81.1, now() - interval '8 hours'),
  ('flow_rate', 'm³/h', 79.5, now() - interval '7.5 hours'),
  ('flow_rate', 'm³/h', 77.3, now() - interval '7 hours'),
  ('flow_rate', 'm³/h', 75.7, now() - interval '6.5 hours'),
  ('flow_rate', 'm³/h', 74.2, now() - interval '6 hours'),
  ('flow_rate', 'm³/h', 72.8, now() - interval '5.5 hours'),
  ('flow_rate', 'm³/h', 71.6, now() - interval '5 hours'),
  ('flow_rate', 'm³/h', 73.9, now() - interval '4.5 hours'),
  ('flow_rate', 'm³/h', 75.4, now() - interval '4 hours'),
  ('flow_rate', 'm³/h', 76.9, now() - interval '3.5 hours'),
  ('flow_rate', 'm³/h', 78.1, now() - interval '3 hours'),
  ('flow_rate', 'm³/h', 76.7, now() - interval '2.5 hours'),
  ('flow_rate', 'm³/h', 75.3, now() - interval '2 hours'),
  ('flow_rate', 'm³/h', 74.6, now() - interval '1.5 hours'),
  ('flow_rate', 'm³/h', 73.8, now() - interval '1 hour'),
  ('flow_rate', 'm³/h', 75.2, now() - interval '30 minutes'),
  ('flow_rate', 'm³/h', 75.0, now() - interval '5 minutes');
